In [3]:
from datatime import datetime,date,timedelta

ModuleNotFoundError: No module named 'datatime'

In [1]:
import pandas as pd

In [2]:
import pandas as pd

df_dates = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "signup_date": ["2024-01-15", "2024-02-20", "2024-03-05", "2024-03-18", "2024-04-10"],
    "last_purchase": ["2024-06-01", "2024-06-15", "2024-07-01", "2024-07-08", "2024-07-12"]
})

df_dates

   customer_id signup_date last_purchase
0          101  2024-01-15    2024-06-01
1          102  2024-02-20    2024-06-15
2          103  2024-03-05    2024-07-01
3          104  2024-03-18    2024-07-08
4          105  2024-04-10    2024-07-12

In [3]:
df_dates.dtypes

customer_id      int64
signup_date        str
last_purchase      str
dtype: object

## Converting to Datetime

In [14]:
df_dates["signup_date"]=pd.to_datetime(df_dates["signup_date"])
df_dates["last_purchase"]=pd.to_datetime(df_dates["last_purchase"])
df_dates.dtypes

customer_id                int64
signup_date       datetime64[us]
last_purchase     datetime64[us]
signup_quarter             int32
signup_dow                 int32
dtype: object

In [5]:
df_dates["signup_year"] = df_dates["signup_date"].dt.year
df_dates["signup_month"] = df_dates["signup_date"].dt.month
df_dates["signup_day"] = df_dates["signup_date"].dt.day

df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day
0,101,2024-01-15,2024-06-01,2024,1,15
1,102,2024-02-20,2024-06-15,2024,2,20
2,103,2024-03-05,2024-07-01,2024,3,5
3,104,2024-03-18,2024-07-08,2024,3,18
4,105,2024-04-10,2024-07-12,2024,4,10

In [6]:
df_dates["signup_month_name"]=df_dates["signup_date"].dt.month_name()
df_dates["signup_day_name"]=df_dates["signup_date"].dt.day_name()
df_dates[["signup_date","signup_month_name","signup_day_name"]]

  signup_date signup_month_name signup_day_name
0  2024-01-15           January          Monday
1  2024-02-20          February         Tuesday
2  2024-03-05             March         Tuesday
3  2024-03-18             March          Monday
4  2024-04-10             April       Wednesday

## Quarter

In [4]:
df_dates["signup_quarter"] = df_dates["signup_date"].dt.quarter
df_dates[["signup_date", "signup_quarter"]]

AttributeError: Can only use .dt accessor with datetimelike values

In [10]:
df_dates["signup_quarter"] = df_dates["signup_date"].dt.quarter
df_dates[["signup_date", "signup_quarter"]]

  signup_date  signup_quarter
0  2024-01-15               1
1  2024-02-20               1
2  2024-03-05               1
3  2024-03-18               1
4  2024-04-10               2

In [12]:
df_dates["signup_quarter"] = df_dates["signup_date"].dt.quarter
df_dates[["signup_date", "signup_quarter"]]

  signup_date  signup_quarter
0  2024-01-15               1
1  2024-02-20               1
2  2024-03-05               1
3  2024-03-18               1
4  2024-04-10               2

## Dayofweek

In [19]:
df_dates["signup_dow"] = df_dates["signup_date"].dt.dayofweek
df_dates[["signup_date", "signup_dow"]]

  signup_date  signup_dow
0  2024-01-15           0
1  2024-02-20           1
2  2024-03-05           1
3  2024-03-18           0
4  2024-04-10           2

## Weekend

In [21]:
df_dates["is_weekend"] = (df_dates["signup_date"].dt.dayofweek >= 5).astype(int)
df_dates[["signup_date", "signup_dow", "is_weekend"]]

  signup_date  signup_dow  is_weekend
0  2024-01-15           0           0
1  2024-02-20           1           0
2  2024-03-05           1           0
3  2024-03-18           0           0
4  2024-04-10           2           0

## Days between

In [23]:
df_dates["days_between_signup_and_purchase"]=(
    df_dates["last_purchase"]-df_dates["signup_date"]
).dt.days
df_dates[["signup_date", "last_purchase", "days_between_signup_and_purchase"]]

  signup_date last_purchase  days_between_signup_and_purchase
0  2024-01-15    2024-06-01                               138
1  2024-02-20    2024-06-15                               116
2  2024-03-05    2024-07-01                               118
3  2024-03-18    2024-07-08                               112
4  2024-04-10    2024-07-12                                93

## Filtering by Date Conditions

In [24]:
df_dates[df_dates["signup_date"]>="2024-03-01"]

,customer_id,signup_date,last_purchase,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
2,103,2024-03-05,2024-07-01,1,1,0,118
3,104,2024-03-18,2024-07-08,1,0,0,112
4,105,2024-04-10,2024-07-12,2,2,0,93

In [25]:
df_dates[df_dates["signup_date"].dt.month ==3]

,customer_id,signup_date,last_purchase,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
2,103,2024-03-05,2024-07-01,1,1,0,118
3,104,2024-03-18,2024-07-08,1,0,0,112

In [26]:
df_dates[df_dates["signup_date"].dt.year == 2024]

,customer_id,signup_date,last_purchase,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,1,0,0,138
1,102,2024-02-20,2024-06-15,1,1,0,116
2,103,2024-03-05,2024-07-01,1,1,0,118
3,104,2024-03-18,2024-07-08,1,0,0,112
4,105,2024-04-10,2024-07-12,2,2,0,93

## sort value

In [27]:
df_dates.sort_values("signup_date")

,customer_id,signup_date,last_purchase,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,1,0,0,138
1,102,2024-02-20,2024-06-15,1,1,0,116
2,103,2024-03-05,2024-07-01,1,1,0,118
3,104,2024-03-18,2024-07-08,1,0,0,112
4,105,2024-04-10,2024-07-12,2,2,0,93

## date range

In [28]:
pd.date_range(start="2024-07-01",periods=7,freq="D")

DatetimeIndex(['2024-07-01', '2024-07-02', '2024-07-03', '2024-07-04',
               '2024-07-05', '2024-07-06', '2024-07-07'],
              dtype='datetime64[us]', freq='D')

In [29]:
pd.date_range(start="2024-07-01",periods=6,freq="MS")

DatetimeIndex(['2024-07-01', '2024-08-01', '2024-09-01', '2024-10-01',
               '2024-11-01', '2024-12-01'],
              dtype='datetime64[us]', freq='MS')

## BOM EOM

In [30]:
import pandas as pd

some_date = pd.Timestamp("2024-07-15")

print(f"Original date: {some_date}")
print(f"Beginning of month: {some_date.to_period('M').start_time}")
print(f"End of month: {some_date.to_period('M').end_time}")

Original date: 2024-07-15 00:00:00
Beginning of month: 2024-07-01 00:00:00
End of month: 2024-07-31 23:59:59.999999

In [31]:
print(f"Beginning of month (date only): {some_date.to_period('M').start_time.date()}")
print(f"End of month (date only): {some_date.to_period('M').end_time.date()}")

Beginning of month (date only): 2024-07-01
End of month (date only): 2024-07-31

In [33]:
df_dates["signup_month"] = df_dates["signup_date"].dt.to_period("M").dt.start_time
df_dates["signup_month"] = df_dates["signup_date"].dt.to_period("M").dt.end_time

df_dates

,customer_id,signup_date,last_purchase,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase,signup_month
0,101,2024-01-15,2024-06-01,1,0,0,138,2024-01-31 23:59:59.999999
1,102,2024-02-20,2024-06-15,1,1,0,116,2024-02-29 23:59:59.999999
2,103,2024-03-05,2024-07-01,1,1,0,118,2024-03-31 23:59:59.999999
3,104,2024-03-18,2024-07-08,1,0,0,112,2024-03-31 23:59:59.999999
4,105,2024-04-10,2024-07-12,2,2,0,93,2024-04-30 23:59:59.999999